### ISSUE TITLE
Date only are parsed in UTC timezone, should be local time

### ISSUE THREAD

**Issue by sdebionne** [bendrucker/postgres-date#2]
commit 47ba3b0cf89814255c31549ae840191f8be3f0df breaks the date only parser.

According to [this link](http://dygraphs.com/date-formats.html), `2011-10-10T14:48:00` are interpreted in the UTC timezone, while `2011-10-10 14:48:00` is in the local time zone -the expected behavior, at least the one given in the comment:

```javascript
  // Force YYYY-MM-DD dates to be parsed as local time
  return DATE.test(isoDate) ?
    new Date(isoDate + 'T00:00:00') :
    null
```

A better implementation may be to use the matches of the regex:

```javascript
  var matches = DATE.exec(isoDate)
  var year = parseInt(matches[1], 10)
  var month = parseInt(matches[2], 10) - 1
  var day = matches[3]
  // Force YYYY-MM-DD dates to be parsed as local time
  return matches ?
    new Date(year, month, day) :
    null
```

**Comment by bendrucker** [comment]
Hey, sorry for missing this. Looking into this now, your example was close but `Date` is weird.

**Comment by tonyxiao** [comment]
@sdebionne @bendrucker why exactly should `date` be parsed in local timezone? We use a lot of `date` columns internally and find UTC a much better representation of date without time component because it's consistent regardless of which machine one runs one and avoid a whole host of timezone related bugs.

**Comment by noinkling** [comment]
I'm with @tonyxiao on this. It makes more sense to match what JS does by default IMO:

```js
> new Date('2019-01-01').toISOString()
"2019-01-01T00:00:00.000Z"
```

And yes that format is explicitly specced in ES: https://tc39.github.io/ecma262/#sec-date-time-string-format

> This format includes date-only forms:
>
> YYYY
> YYYY-MM
> YYYY-MM-DD

**Comment by TiddoLangerak** [comment]
Sorry for digging up this old issue, but I think that the current behaviour is unexpected and leads to bugs. The general concensus is that whenever dealing with dates/times, use UTC. 

To give a concrete example of how this could easily break: GraphQ uses UTC to parse/serialize dates. If I hook up GraphQL to a Postgres database, using this package, then on my Macbook in UK timezone, I can observe the following behaviour from the API:

1. If I send "2022-01-01" through the api, then it'll come back as "2022-01-01"
2. If I send "2022-06-30" through the api, then it'll come back as "2022-06-**29**"

Reason being, June is during daylight savings (UTC+0100), and this causes a date drift due to disagreement between graphql and postgres-date on how to interpret non-utc dates.

I would argue that UTC is always the sensible choice, but also acknowledge that there are probably thousands of applications out there that currently rely on the existing behaviour of `postgres-date`. 

Would you be open to accept a PR that would allow users to opt-in to UTC based parsing? As a concrete proposal, I'd like to add a `parse.inUtc(isoDate)` function that assumes UTC for date/time values without timezone.

**Comment by bendrucker** [comment]
> I would argue that UTC is always the sensible choice

This is not really a matter of opinion or preference, the intent here is to match Postgres behavior.

https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-TIMEZONES

> PostgreSQL assumes your local time zone for any type containing only date or time.

> All timezone-aware dates and times are stored internally in UTC. They are converted to local time in the zone specified by the [TimeZone](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-TIMEZONE) configuration parameter before being displayed to the client.

The `AT TIME ZONE` clause may be helpful in some cases to pass a time zone identifier to the database from the client such that they can agree. In the absence of explicit coordination, the client can only assume that the server has the same local time zone. 

Happy to accept a PR for a method that assumes UTC instead of local for further discussion, `asUTC` seems like a better method name.

**Comment by bendrucker** [comment]
Last note, pg-types dropped this by default in part because of the hazard of representing a date as a JS `Date`, which is really a `DateTime`:

https://github.com/brianc/node-pg-types/pull/121

If you find the timezone behavior to be a hazard you might want to just work with dates as `YYYY-MM-DD` strings.
